version: '3.8'
services:
  api:
    container_name: api
    build: .
    env_file: .env.dev
    ports: 
      - 8082:8082
    volumes: 
      - ./src/:/opt/app/src
      - ./typings/:/opt/app/typings
    networks:
      - default
    depends_on: 
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo:4.2.5
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    networks:
      - default
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_APPLICATION_MODE=master
    networks:
      - default
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - redis
      - mongo
    command: redis:6379 mongo:27017
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
    postgres:
    pgadmin:
