version: '3.8'

services:
  api:
    container_name: api
    build: .
    env_file: .env.dev
    ports: 
      - 8082:8082
    volumes: 
      - ./src/:/opt/app/src
      - ./typings/:/opt/app/typings
    networks:
      - default
    depends_on: 
      - postgres
      - redis
   
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    environment:
      - REDIS_APPLICATION_MODE=master
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
    postgres:
    pgadmin:
